### PR TITLE
Slack channel is now configurable in `organizations.json`

### LINKED ISSUE #41: [slack] Channel is hardcoded.
Channel "#royal-philips" is hardcoded.

### PR DESCRIPTION
**Pull request by JeroenKnoops**
Now you can pass the `slackChannel` in `organizations.json`..

If either `slackChannel` or `slackToken` is missing, no message will be send at all.
See README.md

Closes #41, #42

### CODE REVIEW

**Comment by marcofranssen** [comment]
@bartgolsteijn LGTM

**Comment by marcofranssen** [comment]
@JeroenKnoops seems your commits are not signed.

**Comment by JeroenKnoops** [comment]
> @JeroenKnoops seems your commits are not signed.

Fixed this. I've switched to my old computer and did not yet configured krypt.on

**Pull request merged**
